config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get "home/about"=>"homes#about"
  get 'search' => "searches#search"

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.htm
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  def show
    @book = Book.find(params[:id])
    @booknew = Book.new
    @user=@book.user
    @book_comment = BookComment.new
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      @user=current_user
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def follows
    user = User.find(params[:id])
    @users = user.following_user.all
  end

  def followeds
    user = User.find(params[:id])
    @users = user.follower_user.all
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comment.html.erb
<p>コメント蘭</p>
<table class="table table-borderless">
  <thead>
    <tr>
      <th style="width: 30%"></th>
      <th style="width: 40%"></th>
      <th style="width: 20%"></th>
    </tr>
  </thead>
  <% book.book_comments.each do |book_comment| %>
  <tr>
    <td>
    <%= link_to(book_comment.user) do %>
      <%= image_tag book_comment.user.get_profile_image, size:"50x50" %><br>
      <%= book_comment.user.name %>
    <% end %>
    </td>
    <td><%= book_comment.comment %></td>
    <td>
    <% if book_comment.user == current_user %>
      <%= link_to "削除", book_book_comment_path(book_comment.book, book_comment), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger" %>
    <% end %>
    </td>
  </tr>
  <% end %>
</table>
<div class="formd-group">
<%= form_with model: [book, book_comment] do |f| %>
  <%= f.text_area :comment, class: 'form-control book_comment',rows: '5' %><br>
  <%= f.submit "送信" %>
<% end %>
</div>

app/views/books/_form.html.erb
<%= form_with model:book, url:'/books', method: :post, local:true do |f| %>
  <%= render 'layouts/errors', obj: book %>
  <div class="form-group">
    <%= f.label :Title %>
    <%= f.text_field:title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :Opinion %>
    <%= f.text_area:body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user.id) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td>
        <td><%= render "favorites/favorite",book: book %></td>
        <td>コメント件数：<%= link_to "#{book.book_comments.count}", book_path(book.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <%= render 'layouts/errors', obj: @book %>
  		<h1>Editing Book</h1>
      <%= form_with model: @book, url:book_path(@book.id), method: :patch do |f| %>
      <div class="form-group">
        <%= f.label :Title %>
        <%= f.text_field:title, class: 'form-control book_title' %>
      </div>

      <div class="form-group">
        <%= f.label :Opinion %>
        <%= f.text_area:body, class: 'form-control book_body' %>
      </div>

      <div class="form-group">
        <%= f.submit 'Update Book', class:"btn btn-success" %>
      </div>
      <% end %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  	</div>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <%= render 'searches/searchbox' %>
      <h2>Books</h2>
      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @booknew %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <%= render 'searches/searchbox' %>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"50x50" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <% if user_signed_in? && current_user.id == @book.user_id %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
          <% else %>
            <td><%= render 'favorites/favorite', book: @book %></td>
            <td>コメント件数：<%= @book.book_comments.count %></td>
          <% end %>
        </tr>
      </table>
      <%= render 'book_comments/comment', book: @book, book_comment: @book_comment %>
      <%= render 'book_comments/comment_new', book: @book, book_comment: @book_comment %>
    </div>
  </div>
</div>